#!/usr/bin/env python3
"""Seed the D1 devices table from devices_canonical.json.

Generates a SQL file with INSERT OR IGNORE statements, then optionally
runs it via wrangler.

Usage:
    python3 compat/scripts/seed_d1.py [--execute]

Without --execute, just writes compat/scripts/seed_devices.sql.
With --execute, also runs: wrangler d1 execute reg-compat --file=seed_devices.sql
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CANONICAL_JSON = SCRIPT_DIR / "devices_canonical.json"
OUTPUT_SQL = SCRIPT_DIR / "seed_devices.sql"


def sql_escape(value) -> str:
    """Escape a value for SQLite."""
    if value is None:
        return "NULL"
    if isinstance(value, list):
        return "'" + json.dumps(value).replace("'", "''") + "'"
    s = str(value).replace("'", "''")
    return f"'{s}'"


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed D1 devices table")
    parser.add_argument("--execute", action="store_true",
                        help="Run the SQL via wrangler d1 execute")
    args = parser.parse_args()

    print(f"Reading {CANONICAL_JSON}")
    with open(CANONICAL_JSON) as f:
        devices = json.load(f)

    lines = [
        "-- Auto-generated by seed_d1.py",
        "-- Seed devices table from devices_canonical.json",
        "",
    ]

    inserted = 0
    skipped = 0
    warnings = 0

    for dev in devices:
        device_id = dev["id"]

        # Validate required fields
        if not dev.get("title") or not dev.get("brand"):
            print(f"  WARNING: {device_id} missing title or brand, skipping")
            warnings += 1
            skipped += 1
            continue

        cols = [
            "id", "title", "brand", "type",
            "soc_slug", "soc_name",
            "cpu_arch", "cpu_model", "cpu_cores", "cpu_clock",
            "gpu_model", "gpu_driver", "gpu_api",
            "kernel", "arch", "wiki_url", "image", "na_features",
            "display_size", "display_res", "ram", "storage",
            "wifi_chip", "bt_chip", "has_fan", "compositor",
        ]

        vals = [
            sql_escape(dev["id"]),
            sql_escape(dev["title"]),
            sql_escape(dev["brand"]),
            sql_escape(dev.get("type", "unknown")),
            sql_escape(dev.get("soc_slug")),
            sql_escape(dev.get("soc_name")),
            sql_escape(dev.get("cpu_arch")),
            sql_escape(dev.get("cpu_model")),
            sql_escape(dev.get("cpu_cores")),
            sql_escape(dev.get("cpu_clock")),
            sql_escape(dev.get("gpu_model")),
            sql_escape(dev.get("gpu_driver")),
            sql_escape(dev.get("gpu_api")),
            sql_escape(dev.get("kernel")),
            sql_escape(dev.get("arch")),
            sql_escape(dev.get("wiki_url")),
            sql_escape(dev.get("image")),
            sql_escape(dev.get("na_features")),
            sql_escape(dev.get("display_size")),
            sql_escape(dev.get("display_res")),
            sql_escape(dev.get("ram")),
            sql_escape(dev.get("storage")),
            sql_escape(dev.get("wifi_chip")),
            sql_escape(dev.get("bt_chip")),
            sql_escape(dev.get("has_fan")),
            sql_escape(dev.get("compositor")),
        ]

        line = f"INSERT OR IGNORE INTO devices ({', '.join(cols)}) VALUES ({', '.join(vals)});"
        lines.append(line)
        inserted += 1

    sql_content = "\n".join(lines) + "\n"

    print(f"Writing {OUTPUT_SQL}")
    with open(OUTPUT_SQL, "w") as f:
        f.write(sql_content)

    print(f"\nSummary: {inserted} INSERT statements, {skipped} skipped, {warnings} warnings")

    if args.execute:
        print(f"\nExecuting via wrangler...")
        result = subprocess.run(
            ["npx", "wrangler", "d1", "execute", "reg-compat",
             f"--file={OUTPUT_SQL}"],
            cwd=SCRIPT_DIR.parent / "worker",
            capture_output=True, text=True,
        )
        print(result.stdout)
        if result.returncode != 0:
            print(f"ERROR: {result.stderr}", file=sys.stderr)
            sys.exit(1)
        print("Done!")
    else:
        print(f"\nTo execute: wrangler d1 execute reg-compat --file={OUTPUT_SQL}")
        print("Or re-run with --execute")


if __name__ == "__main__":
    main()
